version: '3'
services:
  app:
    container_name: 'master-page'
    ports: 
      - 3000:3000
    volumes:
      - ./:/home/node/
      - /home/node/node_modules/
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: npm start
    tty: true
    env_file:
      - .env
